<?php
namespace app\common;

use yii\base\Widget;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Json;

class HelloWidget extends Widget
{
    /**
     * @var string $name checkbox的name值
     */
    public $name = 'field-name';

    /**
     * @var array $options checkbox的选项数组
     */
    public $options = [];

    /**
     * @var string $scenario 显示的场景
     */
    public $scenario = null;

    /**
     * @var array $data 提供的数据
     */
    public $data = null;

    /**
     * @var array $exclude 不需要显示的内容
     */
    public $exclude = [];

    /**
     * @var obj $model 模型
     */
    public $model = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @purpose:给每一个需要显示的字段显示一个checkbox
     * @param $item 渲染标签的数据
     */
    public function renderItem($item)
    {
        //可显示的地方，比如 list,export
        $visible = explode(',', $item['visible']);
        //配置数据
        $data = Json::decode($item['data']);
        if (in_array($item['field_name'], $this->exclude)) {
            return;
        }
        if (in_array($this->scenario, $data['visible'])) {
            $this->options = ArrayHelper::merge($this->options, [
                'data' => [
                    'id' => $item['id'],
                    'field' => $item['field_name'],
                    'scenario' => $this->scenario,
                ],
            ]);
            echo Html::beginTag('div', ['class' => 'field-div']);
            echo Html::beginTag('label', [
                'class' => 'field-label',
            ]);
            echo Html::checkbox($this->name, in_array($this->scenario, $visible), $this->options);
            echo ArrayHelper::getValue($this->model, $item['field_name'], $item['field_label']);
            echo Html::endTag('label');
            echo Html::endTag('label');
            echo Html::endTag('div');
        }
    }

    public function run()
    {
        if (empty($this->data)) {
            return;
        }
        echo Html::beginTag('div', ['class' => 'row-div']);
        foreach ($this->data as $item) {
            $this->renderItem($item);
        }
        echo Html::endTag('div');
    }
}
